add missing cstdint include
With Ubuntu 25.10, we get this compilation error:
/home/ldesroches/Workspace/egt/include/egt/types.h:66:1: error:
‘uint32_t’ does not name a type
   66 | uint32_t drm_format(PixelFormat format);
      | ^~~~~~~~

So add the missing include of cstdint to fix it.

Signed-off-by: Ludovic Desroches <ludovic.desroches@microchip.com>
Acked-by: Cyrille Pitchen <cyrille.pitchen@microchip.com>