link libudev for udev_unref and udev_new
These APIs are used in inputlibinput.cpp which is only
compile when HAVE_LIBINPUT is enabled

This shows up when linking with gold linker

../../src/.libs/libegt.so: error: undefined reference to 'udev_new'
../../src/.libs/libegt.so: error: undefined reference to 'udev_unref'
collect2: error: ld returned 1 exit status
Makefile:558: recipe for target 'camera' failed
make[4]: *** [camera] Error 1

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Joshua Henderson <joshua.henderson@microchip.com>